{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "4acaadfb-6aa7-4fd6-957b-01038a864c7b",
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import numpy as np\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "3d7a6f5e-6b9b-42cd-838d-9ad56dd5901e",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Student_ID</th>\n",
       "      <th>Class_Grade</th>\n",
       "      <th>Subject</th>\n",
       "      <th>Marks_Scored</th>\n",
       "      <th>Attendance_Percentage</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>1001</td>\n",
       "      <td>5th</td>\n",
       "      <td>Math</td>\n",
       "      <td>96</td>\n",
       "      <td>85.48</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>1001</td>\n",
       "      <td>5th</td>\n",
       "      <td>Science</td>\n",
       "      <td>79</td>\n",
       "      <td>60.96</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>1001</td>\n",
       "      <td>5th</td>\n",
       "      <td>English</td>\n",
       "      <td>79</td>\n",
       "      <td>74.34</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>1001</td>\n",
       "      <td>5th</td>\n",
       "      <td>Hindi</td>\n",
       "      <td>67</td>\n",
       "      <td>76.44</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>1001</td>\n",
       "      <td>5th</td>\n",
       "      <td>Computers</td>\n",
       "      <td>64</td>\n",
       "      <td>92.20</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>995</th>\n",
       "      <td>1200</td>\n",
       "      <td>8th</td>\n",
       "      <td>Math</td>\n",
       "      <td>69</td>\n",
       "      <td>91.96</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>996</th>\n",
       "      <td>1200</td>\n",
       "      <td>8th</td>\n",
       "      <td>Science</td>\n",
       "      <td>84</td>\n",
       "      <td>57.48</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>997</th>\n",
       "      <td>1200</td>\n",
       "      <td>8th</td>\n",
       "      <td>English</td>\n",
       "      <td>86</td>\n",
       "      <td>80.28</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>998</th>\n",
       "      <td>1200</td>\n",
       "      <td>8th</td>\n",
       "      <td>Hindi</td>\n",
       "      <td>49</td>\n",
       "      <td>80.89</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>999</th>\n",
       "      <td>1200</td>\n",
       "      <td>8th</td>\n",
       "      <td>Computers</td>\n",
       "      <td>76</td>\n",
       "      <td>62.12</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>1000 rows × 5 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "     Student_ID Class_Grade    Subject  Marks_Scored  Attendance_Percentage\n",
       "0          1001         5th       Math            96                  85.48\n",
       "1          1001         5th    Science            79                  60.96\n",
       "2          1001         5th    English            79                  74.34\n",
       "3          1001         5th      Hindi            67                  76.44\n",
       "4          1001         5th  Computers            64                  92.20\n",
       "..          ...         ...        ...           ...                    ...\n",
       "995        1200         8th       Math            69                  91.96\n",
       "996        1200         8th    Science            84                  57.48\n",
       "997        1200         8th    English            86                  80.28\n",
       "998        1200         8th      Hindi            49                  80.89\n",
       "999        1200         8th  Computers            76                  62.12\n",
       "\n",
       "[1000 rows x 5 columns]"
      ]
     },
     "execution_count": 4,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df=pd.read_csv('Data_Exploration_&_Basic_Operations_Student_Performance_dataset - student_performance.csv')\n",
    "df"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "a74aa409-653b-4b44-b9aa-faf46d318a7b",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "   Student_ID Class_Grade    Subject  Marks_Scored  Attendance_Percentage\n",
      "0        1001         5th       Math            96                  85.48\n",
      "1        1001         5th    Science            79                  60.96\n",
      "2        1001         5th    English            79                  74.34\n",
      "3        1001         5th      Hindi            67                  76.44\n",
      "4        1001         5th  Computers            64                  92.20\n",
      "        Student_ID  Marks_Scored  Attendance_Percentage\n",
      "count  1000.000000   1000.000000            1000.000000\n",
      "mean   1100.500000     65.344000              75.338110\n",
      "std      57.763194     20.736144              14.649994\n",
      "min    1001.000000     30.000000              50.030000\n",
      "25%    1050.750000     48.000000              61.890000\n",
      "50%    1100.500000     65.000000              75.425000\n",
      "75%    1150.250000     84.000000              88.255000\n",
      "max    1200.000000    100.000000              99.910000\n",
      "(1000, 5)\n",
      "<class 'pandas.core.frame.DataFrame'>\n",
      "RangeIndex: 1000 entries, 0 to 999\n",
      "Data columns (total 5 columns):\n",
      " #   Column                 Non-Null Count  Dtype  \n",
      "---  ------                 --------------  -----  \n",
      " 0   Student_ID             1000 non-null   int64  \n",
      " 1   Class_Grade            1000 non-null   object \n",
      " 2   Subject                1000 non-null   object \n",
      " 3   Marks_Scored           1000 non-null   int64  \n",
      " 4   Attendance_Percentage  1000 non-null   float64\n",
      "dtypes: float64(1), int64(2), object(2)\n",
      "memory usage: 39.2+ KB\n",
      "None\n"
     ]
    }
   ],
   "source": [
    "#2. Basic Data Exploration\n",
    "print(df.head())\n",
    "print(df.describe())\n",
    "print(df.shape)\n",
    "print(df.info())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "c515cea3-bbbf-4643-9388-b29bf58253c8",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "0      96\n",
       "1      79\n",
       "2      79\n",
       "3      67\n",
       "4      64\n",
       "       ..\n",
       "995    69\n",
       "996    84\n",
       "997    86\n",
       "998    49\n",
       "999    76\n",
       "Name: Marks_Scored, Length: 1000, dtype: int64"
      ]
     },
     "execution_count": 6,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "#3. Selecting Columns and Rows\n",
    "#Single column\n",
    "df['Marks_Scored']"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "127d1c14-b816-4bf7-b981-ff5642fad116",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Student_ID</th>\n",
       "      <th>Subject</th>\n",
       "      <th>Marks_Scored</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>1001</td>\n",
       "      <td>Math</td>\n",
       "      <td>96</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>1001</td>\n",
       "      <td>Science</td>\n",
       "      <td>79</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>1001</td>\n",
       "      <td>English</td>\n",
       "      <td>79</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>1001</td>\n",
       "      <td>Hindi</td>\n",
       "      <td>67</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>1001</td>\n",
       "      <td>Computers</td>\n",
       "      <td>64</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>995</th>\n",
       "      <td>1200</td>\n",
       "      <td>Math</td>\n",
       "      <td>69</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>996</th>\n",
       "      <td>1200</td>\n",
       "      <td>Science</td>\n",
       "      <td>84</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>997</th>\n",
       "      <td>1200</td>\n",
       "      <td>English</td>\n",
       "      <td>86</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>998</th>\n",
       "      <td>1200</td>\n",
       "      <td>Hindi</td>\n",
       "      <td>49</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>999</th>\n",
       "      <td>1200</td>\n",
       "      <td>Computers</td>\n",
       "      <td>76</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>1000 rows × 3 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "     Student_ID    Subject  Marks_Scored\n",
       "0          1001       Math            96\n",
       "1          1001    Science            79\n",
       "2          1001    English            79\n",
       "3          1001      Hindi            67\n",
       "4          1001  Computers            64\n",
       "..          ...        ...           ...\n",
       "995        1200       Math            69\n",
       "996        1200    Science            84\n",
       "997        1200    English            86\n",
       "998        1200      Hindi            49\n",
       "999        1200  Computers            76\n",
       "\n",
       "[1000 rows x 3 columns]"
      ]
     },
     "execution_count": 7,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "#Multiple column\n",
    "df[['Student_ID', 'Subject', 'Marks_Scored']]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "680e174e-a263-46de-a030-8eb1b2b87f6b",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "     Student_ID Class_Grade    Subject  Marks_Scored  Attendance_Percentage\n",
      "0          1001         5th       Math            96                  85.48\n",
      "13         1003         4th      Hindi           100                  92.98\n",
      "14         1003         4th  Computers            83                  60.58\n",
      "16         1004        12th    Science            86                  80.97\n",
      "17         1004        12th    English            83                  75.82\n",
      "..          ...         ...        ...           ...                    ...\n",
      "988        1198         8th      Hindi            94                  85.93\n",
      "992        1199        11th    English            88                  66.33\n",
      "993        1199        11th      Hindi            94                  76.40\n",
      "996        1200         8th    Science            84                  57.48\n",
      "997        1200         8th    English            86                  80.28\n",
      "\n",
      "[288 rows x 5 columns]\n",
      "     Student_ID Class_Grade    Subject  Marks_Scored  Attendance_Percentage\n",
      "0          1001         5th       Math            96                  85.48\n",
      "3          1001         5th      Hindi            67                  76.44\n",
      "4          1001         5th  Computers            64                  92.20\n",
      "9          1002        12th  Computers            79                  78.70\n",
      "11         1003         4th    Science            70                  99.82\n",
      "..          ...         ...        ...           ...                    ...\n",
      "993        1199        11th      Hindi            94                  76.40\n",
      "994        1199        11th  Computers            41                  84.27\n",
      "995        1200         8th       Math            69                  91.96\n",
      "997        1200         8th    English            86                  80.28\n",
      "998        1200         8th      Hindi            49                  80.89\n",
      "\n",
      "[509 rows x 5 columns]\n"
     ]
    }
   ],
   "source": [
    "#Select Rows Based on conditions related to attendance, marks scored, etc.\n",
    "print(df[df['Marks_Scored'] > 80])\n",
    "print(df[df['Attendance_Percentage'] > 75])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "4f4e9970-61da-4533-847d-65618dbeeb5f",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Student_ID</th>\n",
       "      <th>Class_Grade</th>\n",
       "      <th>Subject</th>\n",
       "      <th>Marks_Scored</th>\n",
       "      <th>Attendance_Percentage</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>13</th>\n",
       "      <td>1003</td>\n",
       "      <td>4th</td>\n",
       "      <td>Hindi</td>\n",
       "      <td>100</td>\n",
       "      <td>92.98</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>410</th>\n",
       "      <td>1083</td>\n",
       "      <td>10th</td>\n",
       "      <td>Math</td>\n",
       "      <td>100</td>\n",
       "      <td>80.62</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>46</th>\n",
       "      <td>1010</td>\n",
       "      <td>3th</td>\n",
       "      <td>Science</td>\n",
       "      <td>100</td>\n",
       "      <td>99.32</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>52</th>\n",
       "      <td>1011</td>\n",
       "      <td>8th</td>\n",
       "      <td>English</td>\n",
       "      <td>100</td>\n",
       "      <td>88.08</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>343</th>\n",
       "      <td>1069</td>\n",
       "      <td>11th</td>\n",
       "      <td>Hindi</td>\n",
       "      <td>100</td>\n",
       "      <td>65.39</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>633</th>\n",
       "      <td>1127</td>\n",
       "      <td>9th</td>\n",
       "      <td>Hindi</td>\n",
       "      <td>30</td>\n",
       "      <td>96.53</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>606</th>\n",
       "      <td>1122</td>\n",
       "      <td>4th</td>\n",
       "      <td>Science</td>\n",
       "      <td>30</td>\n",
       "      <td>60.23</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>93</th>\n",
       "      <td>1019</td>\n",
       "      <td>9th</td>\n",
       "      <td>Hindi</td>\n",
       "      <td>30</td>\n",
       "      <td>71.44</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>449</th>\n",
       "      <td>1090</td>\n",
       "      <td>2th</td>\n",
       "      <td>Computers</td>\n",
       "      <td>30</td>\n",
       "      <td>63.94</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>367</th>\n",
       "      <td>1074</td>\n",
       "      <td>4th</td>\n",
       "      <td>English</td>\n",
       "      <td>30</td>\n",
       "      <td>82.26</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>1000 rows × 5 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "     Student_ID Class_Grade    Subject  Marks_Scored  Attendance_Percentage\n",
       "13         1003         4th      Hindi           100                  92.98\n",
       "410        1083        10th       Math           100                  80.62\n",
       "46         1010         3th    Science           100                  99.32\n",
       "52         1011         8th    English           100                  88.08\n",
       "343        1069        11th      Hindi           100                  65.39\n",
       "..          ...         ...        ...           ...                    ...\n",
       "633        1127         9th      Hindi            30                  96.53\n",
       "606        1122         4th    Science            30                  60.23\n",
       "93         1019         9th      Hindi            30                  71.44\n",
       "449        1090         2th  Computers            30                  63.94\n",
       "367        1074         4th    English            30                  82.26\n",
       "\n",
       "[1000 rows x 5 columns]"
      ]
     },
     "execution_count": 9,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "#4. Sorting Data\n",
    "#sort by marks\n",
    "df.sort_values(by='Marks_Scored', ascending=False)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "8f85b212-3f87-469f-8776-2868a95d9fe3",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Student_ID</th>\n",
       "      <th>Class_Grade</th>\n",
       "      <th>Subject</th>\n",
       "      <th>Marks_Scored</th>\n",
       "      <th>Attendance_Percentage</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>519</th>\n",
       "      <td>1104</td>\n",
       "      <td>6th</td>\n",
       "      <td>Computers</td>\n",
       "      <td>100</td>\n",
       "      <td>83.49</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>619</th>\n",
       "      <td>1124</td>\n",
       "      <td>6th</td>\n",
       "      <td>Computers</td>\n",
       "      <td>100</td>\n",
       "      <td>88.55</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>904</th>\n",
       "      <td>1181</td>\n",
       "      <td>2th</td>\n",
       "      <td>Computers</td>\n",
       "      <td>100</td>\n",
       "      <td>54.57</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>919</th>\n",
       "      <td>1184</td>\n",
       "      <td>12th</td>\n",
       "      <td>Computers</td>\n",
       "      <td>100</td>\n",
       "      <td>96.78</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>79</th>\n",
       "      <td>1016</td>\n",
       "      <td>1th</td>\n",
       "      <td>Computers</td>\n",
       "      <td>99</td>\n",
       "      <td>53.79</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>896</th>\n",
       "      <td>1180</td>\n",
       "      <td>2th</td>\n",
       "      <td>Science</td>\n",
       "      <td>32</td>\n",
       "      <td>50.61</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>311</th>\n",
       "      <td>1063</td>\n",
       "      <td>5th</td>\n",
       "      <td>Science</td>\n",
       "      <td>31</td>\n",
       "      <td>99.91</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>231</th>\n",
       "      <td>1047</td>\n",
       "      <td>4th</td>\n",
       "      <td>Science</td>\n",
       "      <td>30</td>\n",
       "      <td>98.21</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>606</th>\n",
       "      <td>1122</td>\n",
       "      <td>4th</td>\n",
       "      <td>Science</td>\n",
       "      <td>30</td>\n",
       "      <td>60.23</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>686</th>\n",
       "      <td>1138</td>\n",
       "      <td>3th</td>\n",
       "      <td>Science</td>\n",
       "      <td>30</td>\n",
       "      <td>56.30</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>1000 rows × 5 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "     Student_ID Class_Grade    Subject  Marks_Scored  Attendance_Percentage\n",
       "519        1104         6th  Computers           100                  83.49\n",
       "619        1124         6th  Computers           100                  88.55\n",
       "904        1181         2th  Computers           100                  54.57\n",
       "919        1184        12th  Computers           100                  96.78\n",
       "79         1016         1th  Computers            99                  53.79\n",
       "..          ...         ...        ...           ...                    ...\n",
       "896        1180         2th    Science            32                  50.61\n",
       "311        1063         5th    Science            31                  99.91\n",
       "231        1047         4th    Science            30                  98.21\n",
       "606        1122         4th    Science            30                  60.23\n",
       "686        1138         3th    Science            30                  56.30\n",
       "\n",
       "[1000 rows x 5 columns]"
      ]
     },
     "execution_count": 10,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "#sort by marks and subject\n",
    "df.sort_values(by=['Subject', 'Marks_Scored'], ascending=[True, False])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "id": "09ffada1-5856-4589-996d-0c456cd337ff",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Student_ID</th>\n",
       "      <th>Class_Grade</th>\n",
       "      <th>Subject</th>\n",
       "      <th>Marks_Scored</th>\n",
       "      <th>Attendance_Percentage</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>1001</td>\n",
       "      <td>5th</td>\n",
       "      <td>Math</td>\n",
       "      <td>96</td>\n",
       "      <td>85.48</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>13</th>\n",
       "      <td>1003</td>\n",
       "      <td>4th</td>\n",
       "      <td>Hindi</td>\n",
       "      <td>100</td>\n",
       "      <td>92.98</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>16</th>\n",
       "      <td>1004</td>\n",
       "      <td>12th</td>\n",
       "      <td>Science</td>\n",
       "      <td>86</td>\n",
       "      <td>80.97</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>45</th>\n",
       "      <td>1010</td>\n",
       "      <td>3th</td>\n",
       "      <td>Math</td>\n",
       "      <td>91</td>\n",
       "      <td>98.01</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>46</th>\n",
       "      <td>1010</td>\n",
       "      <td>3th</td>\n",
       "      <td>Science</td>\n",
       "      <td>100</td>\n",
       "      <td>99.32</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>941</th>\n",
       "      <td>1189</td>\n",
       "      <td>2th</td>\n",
       "      <td>Science</td>\n",
       "      <td>97</td>\n",
       "      <td>96.75</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>956</th>\n",
       "      <td>1192</td>\n",
       "      <td>12th</td>\n",
       "      <td>Science</td>\n",
       "      <td>96</td>\n",
       "      <td>91.04</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>978</th>\n",
       "      <td>1196</td>\n",
       "      <td>4th</td>\n",
       "      <td>Hindi</td>\n",
       "      <td>86</td>\n",
       "      <td>83.37</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>988</th>\n",
       "      <td>1198</td>\n",
       "      <td>8th</td>\n",
       "      <td>Hindi</td>\n",
       "      <td>94</td>\n",
       "      <td>85.93</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>997</th>\n",
       "      <td>1200</td>\n",
       "      <td>8th</td>\n",
       "      <td>English</td>\n",
       "      <td>86</td>\n",
       "      <td>80.28</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>105 rows × 5 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "     Student_ID Class_Grade  Subject  Marks_Scored  Attendance_Percentage\n",
       "0          1001         5th     Math            96                  85.48\n",
       "13         1003         4th    Hindi           100                  92.98\n",
       "16         1004        12th  Science            86                  80.97\n",
       "45         1010         3th     Math            91                  98.01\n",
       "46         1010         3th  Science           100                  99.32\n",
       "..          ...         ...      ...           ...                    ...\n",
       "941        1189         2th  Science            97                  96.75\n",
       "956        1192        12th  Science            96                  91.04\n",
       "978        1196         4th    Hindi            86                  83.37\n",
       "988        1198         8th    Hindi            94                  85.93\n",
       "997        1200         8th  English            86                  80.28\n",
       "\n",
       "[105 rows x 5 columns]"
      ]
     },
     "execution_count": 11,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "#5. Filtering Data\n",
    "#High performers\n",
    "df[(df['Marks_Scored'] > 85) & (df['Attendance_Percentage'] > 80)]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "id": "38f99228-423d-4a62-bd28-b6361141ba74",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Student_ID</th>\n",
       "      <th>Class_Grade</th>\n",
       "      <th>Subject</th>\n",
       "      <th>Marks_Scored</th>\n",
       "      <th>Attendance_Percentage</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>1001</td>\n",
       "      <td>5th</td>\n",
       "      <td>Math</td>\n",
       "      <td>96</td>\n",
       "      <td>85.48</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>5</th>\n",
       "      <td>1002</td>\n",
       "      <td>12th</td>\n",
       "      <td>Math</td>\n",
       "      <td>64</td>\n",
       "      <td>54.76</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>10</th>\n",
       "      <td>1003</td>\n",
       "      <td>4th</td>\n",
       "      <td>Math</td>\n",
       "      <td>60</td>\n",
       "      <td>58.84</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>15</th>\n",
       "      <td>1004</td>\n",
       "      <td>12th</td>\n",
       "      <td>Math</td>\n",
       "      <td>37</td>\n",
       "      <td>77.19</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>20</th>\n",
       "      <td>1005</td>\n",
       "      <td>3th</td>\n",
       "      <td>Math</td>\n",
       "      <td>78</td>\n",
       "      <td>81.69</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>975</th>\n",
       "      <td>1196</td>\n",
       "      <td>4th</td>\n",
       "      <td>Math</td>\n",
       "      <td>91</td>\n",
       "      <td>60.28</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>980</th>\n",
       "      <td>1197</td>\n",
       "      <td>1th</td>\n",
       "      <td>Math</td>\n",
       "      <td>64</td>\n",
       "      <td>56.50</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>985</th>\n",
       "      <td>1198</td>\n",
       "      <td>8th</td>\n",
       "      <td>Math</td>\n",
       "      <td>45</td>\n",
       "      <td>75.96</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>990</th>\n",
       "      <td>1199</td>\n",
       "      <td>11th</td>\n",
       "      <td>Math</td>\n",
       "      <td>32</td>\n",
       "      <td>95.11</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>995</th>\n",
       "      <td>1200</td>\n",
       "      <td>8th</td>\n",
       "      <td>Math</td>\n",
       "      <td>69</td>\n",
       "      <td>91.96</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>200 rows × 5 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "     Student_ID Class_Grade Subject  Marks_Scored  Attendance_Percentage\n",
       "0          1001         5th    Math            96                  85.48\n",
       "5          1002        12th    Math            64                  54.76\n",
       "10         1003         4th    Math            60                  58.84\n",
       "15         1004        12th    Math            37                  77.19\n",
       "20         1005         3th    Math            78                  81.69\n",
       "..          ...         ...     ...           ...                    ...\n",
       "975        1196         4th    Math            91                  60.28\n",
       "980        1197         1th    Math            64                  56.50\n",
       "985        1198         8th    Math            45                  75.96\n",
       "990        1199        11th    Math            32                  95.11\n",
       "995        1200         8th    Math            69                  91.96\n",
       "\n",
       "[200 rows x 5 columns]"
      ]
     },
     "execution_count": 12,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "#Specific subject\n",
    "df[df['Subject'] == 'Math']"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "id": "2a3c5fb3-f439-4d32-b461-c58b22f615d8",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "Subject\n",
       "English      67.610\n",
       "Math         66.055\n",
       "Computers    65.350\n",
       "Science      64.090\n",
       "Hindi        63.615\n",
       "Name: Marks_Scored, dtype: float64"
      ]
     },
     "execution_count": 13,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "#6.Group and sort data\n",
    "#Average Marks by Subject\n",
    "df.groupby('Subject')['Marks_Scored'].mean().sort_values(ascending=False)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "id": "b33c4fa4-f08d-4caf-9de2-d5237a57efa6",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "Class_Grade\n",
       "10th    70.082222\n",
       "6th     72.672714\n",
       "1th     74.067176\n",
       "12th    74.289077\n",
       "2th     75.205158\n",
       "5th     75.306182\n",
       "9th     75.854909\n",
       "4th     76.043059\n",
       "11th    76.613882\n",
       "3th     76.702095\n",
       "8th     76.843111\n",
       "7th     77.366727\n",
       "Name: Attendance_Percentage, dtype: float64"
      ]
     },
     "execution_count": 14,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "#Average Attendance by Grade\n",
    "df.groupby('Class_Grade')['Attendance_Percentage'].mean().sort_values()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "id": "e00955e2-3abd-4a92-ab87-b36a6abee3d1",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "     Student_ID Class_Grade    Subject  Marks_Scored  Attendance_Percentage  \\\n",
      "0          1001         5th       Math            96                  85.48   \n",
      "1          1001         5th    Science            79                  60.96   \n",
      "2          1001         5th    English            79                  74.34   \n",
      "3          1001         5th      Hindi            67                  76.44   \n",
      "4          1001         5th  Computers            64                  92.20   \n",
      "..          ...         ...        ...           ...                    ...   \n",
      "995        1200         8th       Math            69                  91.96   \n",
      "996        1200         8th    Science            84                  57.48   \n",
      "997        1200         8th    English            86                  80.28   \n",
      "998        1200         8th      Hindi            49                  80.89   \n",
      "999        1200         8th  Computers            76                  62.12   \n",
      "\n",
      "    Grade  \n",
      "0       A  \n",
      "1       B  \n",
      "2       B  \n",
      "3       C  \n",
      "4       C  \n",
      "..    ...  \n",
      "995     C  \n",
      "996     B  \n",
      "997     B  \n",
      "998     D  \n",
      "999     B  \n",
      "\n",
      "[1000 rows x 6 columns]\n"
     ]
    }
   ],
   "source": [
    "#7. Adding New Columns\n",
    "def grade(marks):\n",
    "    if marks >= 90:\n",
    "        return 'A'\n",
    "    elif marks >= 75:\n",
    "        return 'B'\n",
    "    elif marks >= 60:\n",
    "        return 'C'\n",
    "    else:\n",
    "        return 'D'\n",
    "\n",
    "df['Grade'] = df['Marks_Scored'].apply(grade)\n",
    "print(df)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "id": "1b2e0798-713e-40ce-a5b0-abc4e2b2c713",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Subject      Computers    English      Hindi       Math    Science\n",
      "Class_Grade                                                       \n",
      "10th         56.777778  61.333333  60.555556  77.888889  61.222222\n",
      "11th         67.470588  70.823529  66.058824  69.058824  61.705882\n",
      "12th         61.153846  72.076923  58.692308  61.461538  67.000000\n",
      "1th          69.235294  78.764706  68.764706  65.823529  67.235294\n",
      "2th          72.631579  65.631579  64.052632  70.210526  66.368421\n",
      "3th          60.047619  70.952381  58.333333  63.095238  64.095238\n",
      "4th          63.588235  57.470588  69.647059  64.647059  56.588235\n",
      "5th          62.954545  66.363636  68.681818  64.954545  60.090909\n",
      "6th          69.785714  61.214286  57.285714  66.357143  60.142857\n",
      "7th          71.727273  70.000000  54.363636  69.636364  75.000000\n",
      "8th          71.444444  63.666667  64.500000  60.111111  66.333333\n",
      "9th          58.227273  70.136364  64.772727  66.090909  66.000000\n"
     ]
    }
   ],
   "source": [
    "#8. Pivot Table (Summary Analysis)\n",
    "#Average Marks per Subject per Grade\n",
    "pivot_table = df.pivot_table(\n",
    "    values='Marks_Scored',\n",
    "    index='Class_Grade',\n",
    "    columns='Subject',\n",
    "    aggfunc='mean'\n",
    ")\n",
    "\n",
    "print(pivot_table)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 20,
   "id": "c34bbe84-3d2d-417d-a99e-ef8aad0a5e42",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Student_ID</th>\n",
       "      <th>Class_Grade</th>\n",
       "      <th>Subject</th>\n",
       "      <th>Marks_Scored</th>\n",
       "      <th>Attendance_Percentage</th>\n",
       "      <th>Grade</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>1001</td>\n",
       "      <td>5th</td>\n",
       "      <td>Math</td>\n",
       "      <td>96</td>\n",
       "      <td>85.48</td>\n",
       "      <td>A</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>1001</td>\n",
       "      <td>5th</td>\n",
       "      <td>Science</td>\n",
       "      <td>79</td>\n",
       "      <td>60.96</td>\n",
       "      <td>B</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>1001</td>\n",
       "      <td>5th</td>\n",
       "      <td>English</td>\n",
       "      <td>79</td>\n",
       "      <td>74.34</td>\n",
       "      <td>B</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>1001</td>\n",
       "      <td>5th</td>\n",
       "      <td>Hindi</td>\n",
       "      <td>67</td>\n",
       "      <td>76.44</td>\n",
       "      <td>C</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>1001</td>\n",
       "      <td>5th</td>\n",
       "      <td>Computers</td>\n",
       "      <td>64</td>\n",
       "      <td>92.20</td>\n",
       "      <td>C</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>995</th>\n",
       "      <td>1200</td>\n",
       "      <td>8th</td>\n",
       "      <td>Math</td>\n",
       "      <td>69</td>\n",
       "      <td>91.96</td>\n",
       "      <td>C</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>996</th>\n",
       "      <td>1200</td>\n",
       "      <td>8th</td>\n",
       "      <td>Science</td>\n",
       "      <td>84</td>\n",
       "      <td>57.48</td>\n",
       "      <td>B</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>997</th>\n",
       "      <td>1200</td>\n",
       "      <td>8th</td>\n",
       "      <td>English</td>\n",
       "      <td>86</td>\n",
       "      <td>80.28</td>\n",
       "      <td>B</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>998</th>\n",
       "      <td>1200</td>\n",
       "      <td>8th</td>\n",
       "      <td>Hindi</td>\n",
       "      <td>49</td>\n",
       "      <td>80.89</td>\n",
       "      <td>D</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>999</th>\n",
       "      <td>1200</td>\n",
       "      <td>8th</td>\n",
       "      <td>Computers</td>\n",
       "      <td>76</td>\n",
       "      <td>62.12</td>\n",
       "      <td>B</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>1000 rows × 6 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "     Student_ID Class_Grade    Subject  Marks_Scored  Attendance_Percentage  \\\n",
       "0          1001         5th       Math            96                  85.48   \n",
       "1          1001         5th    Science            79                  60.96   \n",
       "2          1001         5th    English            79                  74.34   \n",
       "3          1001         5th      Hindi            67                  76.44   \n",
       "4          1001         5th  Computers            64                  92.20   \n",
       "..          ...         ...        ...           ...                    ...   \n",
       "995        1200         8th       Math            69                  91.96   \n",
       "996        1200         8th    Science            84                  57.48   \n",
       "997        1200         8th    English            86                  80.28   \n",
       "998        1200         8th      Hindi            49                  80.89   \n",
       "999        1200         8th  Computers            76                  62.12   \n",
       "\n",
       "    Grade  \n",
       "0       A  \n",
       "1       B  \n",
       "2       B  \n",
       "3       C  \n",
       "4       C  \n",
       "..    ...  \n",
       "995     C  \n",
       "996     B  \n",
       "997     B  \n",
       "998     D  \n",
       "999     B  \n",
       "\n",
       "[1000 rows x 6 columns]"
      ]
     },
     "execution_count": 20,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "#9. Handle Missing Values\n",
    "df.isnull().sum()\n",
    "df.fillna(0, inplace=True)\n",
    "df.dropna(inplace=True)\n",
    "df"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 22,
   "id": "4c5c7f3f-0665-46e9-8212-123f9cc49533",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Student_ID</th>\n",
       "      <th>Class_Grade</th>\n",
       "      <th>Subject</th>\n",
       "      <th>Marks</th>\n",
       "      <th>Attendance</th>\n",
       "      <th>Grade</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>1001</td>\n",
       "      <td>5th</td>\n",
       "      <td>Math</td>\n",
       "      <td>96</td>\n",
       "      <td>85.48</td>\n",
       "      <td>A</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>1001</td>\n",
       "      <td>5th</td>\n",
       "      <td>Science</td>\n",
       "      <td>79</td>\n",
       "      <td>60.96</td>\n",
       "      <td>B</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>1001</td>\n",
       "      <td>5th</td>\n",
       "      <td>English</td>\n",
       "      <td>79</td>\n",
       "      <td>74.34</td>\n",
       "      <td>B</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>1001</td>\n",
       "      <td>5th</td>\n",
       "      <td>Hindi</td>\n",
       "      <td>67</td>\n",
       "      <td>76.44</td>\n",
       "      <td>C</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>1001</td>\n",
       "      <td>5th</td>\n",
       "      <td>Computers</td>\n",
       "      <td>64</td>\n",
       "      <td>92.20</td>\n",
       "      <td>C</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>995</th>\n",
       "      <td>1200</td>\n",
       "      <td>8th</td>\n",
       "      <td>Math</td>\n",
       "      <td>69</td>\n",
       "      <td>91.96</td>\n",
       "      <td>C</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>996</th>\n",
       "      <td>1200</td>\n",
       "      <td>8th</td>\n",
       "      <td>Science</td>\n",
       "      <td>84</td>\n",
       "      <td>57.48</td>\n",
       "      <td>B</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>997</th>\n",
       "      <td>1200</td>\n",
       "      <td>8th</td>\n",
       "      <td>English</td>\n",
       "      <td>86</td>\n",
       "      <td>80.28</td>\n",
       "      <td>B</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>998</th>\n",
       "      <td>1200</td>\n",
       "      <td>8th</td>\n",
       "      <td>Hindi</td>\n",
       "      <td>49</td>\n",
       "      <td>80.89</td>\n",
       "      <td>D</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>999</th>\n",
       "      <td>1200</td>\n",
       "      <td>8th</td>\n",
       "      <td>Computers</td>\n",
       "      <td>76</td>\n",
       "      <td>62.12</td>\n",
       "      <td>B</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>1000 rows × 6 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "     Student_ID Class_Grade    Subject  Marks  Attendance Grade\n",
       "0          1001         5th       Math     96       85.48     A\n",
       "1          1001         5th    Science     79       60.96     B\n",
       "2          1001         5th    English     79       74.34     B\n",
       "3          1001         5th      Hindi     67       76.44     C\n",
       "4          1001         5th  Computers     64       92.20     C\n",
       "..          ...         ...        ...    ...         ...   ...\n",
       "995        1200         8th       Math     69       91.96     C\n",
       "996        1200         8th    Science     84       57.48     B\n",
       "997        1200         8th    English     86       80.28     B\n",
       "998        1200         8th      Hindi     49       80.89     D\n",
       "999        1200         8th  Computers     76       62.12     B\n",
       "\n",
       "[1000 rows x 6 columns]"
      ]
     },
     "execution_count": 22,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "#10. Rename Columns\n",
    "df.rename(columns={\n",
    "    'Marks_Scored': 'Marks',\n",
    "    'Attendance_Percentage': 'Attendance'\n",
    "}, inplace=True)\n",
    "df"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 23,
   "id": "94d038a4-6d99-4aad-acf3-0e719f151771",
   "metadata": {},
   "outputs": [],
   "source": [
    "#Export data to csv\n",
    "df.to_csv(\"updated_student_data.csv\", index=False)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "0547b668-3564-4871-bc66-a5c3408c7c49",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
